Fix MSVC CI builds in windows-2022 environments
libxmp/libxmp pull request #577
Opened 2022-02-24 21:14 UTC by ccawley2011

2022-02-24 21:36 UTC, sezero commented
As far as I can see, the difference in nmake builds in nmake prepare step is an additional `Setting is_x64_arch` and `Setting __DOTNET_ADD_64BIT` instead of `Setting __DOTNET_ADD_32BIT`: So, we can tell that builds for x86 and x64 are setup and working properly, yes?

This is OK by me. @AliceLR?

2022-02-25 06:47 UTC, AliceLR requested changes

2022-02-25 06:47 UTC, AliceLR commented on .github/workflows/regression.yaml
> +          nmake -f Makefile.vc
The `cd test-dev` part is required... otherwise this just tries to build libxmp itself again and does nothing.

2022-02-25 06:48 UTC, AliceLR commented
> So, we can tell that builds for x86 and x64 are setup and working properly, yes?

Looks like it. nmake is reporting the correct architecture in its logs (GitHub collapses that part for some reason).

2022-02-25 10:39 UTC, sezero approved these changes

2022-02-25 10:41 UTC, sezero commented
@AliceLR: This awaits your approval.

2022-02-25 13:53 UTC, AliceLR approved these changes
The CI logs look good now, thanks!

2022-02-25 13:53 UTC, merged